import { NextResponse } from 'next/server';
import { db } from "@/lib/db";
import { generateAgentMetadata } from "@/lib/llm";
import { sanitizeTopic } from "@/lib/topics";
import { createClient } from '@/lib/supabase/server';
import { generateEmbedding, generateAgentEmbeddingText } from "@/lib/embeddings";

export async function POST(req) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    let { 
      name, 
      emoji, 
      topic, 
      subTopic, 
      colorHex, 
      persona, 
      responseStyle
    } = body;

    // Trim inputs
    name = name?.trim();
    topic = topic?.trim();
    subTopic = subTopic?.trim();
    persona = persona?.trim();
    responseStyle = responseStyle?.trim();

    // Sanitize Topic immediately
    topic = sanitizeTopic(topic);

    // AI Generation - Persona is ALWAYS refined/generated by LLM
    // We trigger AI Architect to build a world-class persona even if some fields are already provided
    console.log(`[API] Triggering AI Architect for persona refinement and field completion...`);
    try {
      const aiMetadata = await generateAgentMetadata({
        name,
        topic,
        subTopic,
        personaDetails: persona, // User's custom directives/description
        responseStyle,
        emoji,
        colorHex: colorHex || 'AI'
      });

      // Fill in missing values with AI generated content
      console.log(`[API] AI Metadata response keys:`, Object.keys(aiMetadata || {}));
      
      name = name || aiMetadata.name;
      persona = aiMetadata.persona; // ALWAYS use the AI-generated/refined persona
      emoji = emoji || aiMetadata.emoji;
      responseStyle = (responseStyle && responseStyle !== 'AI will generate') ? responseStyle : aiMetadata.response_style;
      colorHex = (colorHex && colorHex !== 'AI') ? colorHex : aiMetadata.color_hex;
      subTopic = aiMetadata.sub_topic || subTopic;
      
      console.log(`[API] Resolved Identity - Name: ${name}, Persona (chars): ${persona?.length || 0}`);
    } catch (aiError) {
      console.error("[API] AI Metadata generation failed:", aiError);
      // Fallback: If AI fails but we already have name/topic/persona from user, we can still proceed
    }

    // Final Validation check before DB insert
    if (!name || !persona) {
      console.error(`[API] Validation failed: Name or Persona is missing after generation. (Name: ${name}, Persona: ${persona})`);
      return NextResponse.json({ 
        error: "Agent Identity Incomplete. Please provide a Name and Persona details, or refine the Topic so AI can generate them." 
      }, { status: 400 });
    }

    // Slug generation
    const baseSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const randomSuffix = Math.random().toString(36).substring(2, 6);
    const slug = `${baseSlug}-${randomSuffix}`;

    // Generate Embedding
    let personaEmbedding = null;
    try {
      const embeddingText = generateAgentEmbeddingText({ name, topic, sub_topic: subTopic, persona });
      const vector = await generateEmbedding(embeddingText);
      personaEmbedding = `[${vector.join(',')}]`;
      console.log(`[API] Generated persona embedding (length: ${vector.length})`);
    } catch (embedError) {
      console.error("[API] Failed to generate persona embedding:", embedError);
    }

    // Database Insert (is_active: true, schema strictly adhered to)
    const { data: newAgent, error: insertError } = await db
      .from('agents')
      .insert({
        name,
        slug,
        emoji: emoji || '🤖',
        topic,
        sub_topic: subTopic || '',
        persona,
        response_style: responseStyle || 'Authentic',
        color_hex: colorHex || '#eaff04',
        language: 'en',
        country: 'World',
        is_active: true,
        creator_id: user.id,
        persona_embedding: personaEmbedding
      });

    if (insertError) throw insertError;

    // AUTOMATIC FOLLOW: Creator always follows their created agent
    try {
      await db.query(`
        INSERT INTO user_follows (user_id, agent_id)
        VALUES ($1, $2) ON CONFLICT DO NOTHING
      `, [user.id, newAgent.id]);
      
      // Update follow count
      await db.query(`UPDATE agents SET follower_count = follower_count + 1 WHERE id = $1`, [newAgent.id]);
      
      // Update the local object returned to the user if they care
      newAgent.follower_count = (newAgent.follower_count || 0) + 1;
    } catch (followError) {
      console.error("[API] Failed to auto-follow created agent:", followError);
      // We don't fail the whole creation for this, but it shouldn't happen
    }

    return NextResponse.json({ success: true, agent: newAgent }, { status: 200 });
  } catch (error) {
    console.error("[POST /api/agents] Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

