import { NextResponse } from 'next/server';
import { db } from "@/lib/db";
import { generateAgentMetadata } from "@/lib/llm";

export async function POST(req) {
  try {
    const body = await req.json();
    let { 
      name, 
      emoji, 
      topic, 
      subTopic, 
      colorHex, 
      persona, 
      responseStyle
    } = body;

    // Validation: Only Topic is strictly mandatory now
    if (!topic) {
      return NextResponse.json({ error: "Topic is required." }, { status: 400 });
    }

    // AI Generation - Persona is ALWAYS refined/generated by LLM
    // We trigger AI Architect to build a world-class persona even if some fields are already provided
    console.log(`[API] Triggering AI Architect for persona refinement and field completion...`);
    try {
      const aiMetadata = await generateAgentMetadata({
        name,
        topic,
        subTopic,
        personaDetails: persona, // User's custom directives/description
        responseStyle,
        emoji,
        colorHex: colorHex || 'AI'
      });

      // Fill in missing values with AI generated content
      console.log(`[API] AI Metadata response keys:`, Object.keys(aiMetadata || {}));
      
      // --- DEBUG LOGGING TO FILE ---
      const fs = require('fs');
      const logContent = `\n[${new Date().toISOString()}] Topic: ${topic}, SubTopic: ${subTopic}\n` +
                         `AI Response Keys: ${Object.keys(aiMetadata || {}).join(', ')}\n` +
                         `Persona Snippet: ${aiMetadata.persona?.slice(0, 100) || 'NULL'}\n` +
                         `-----------------------------------\n`;
      fs.appendFileSync('/Users/igalemona/repos/FeedSphere/feedsphere/debug_api.log', logContent);
      // -----------------------------

      name = name || aiMetadata.name;
      persona = aiMetadata.persona; // ALWAYS use the AI-generated/refined persona
      emoji = emoji || aiMetadata.emoji;
      responseStyle = (responseStyle && responseStyle !== 'AI will generate') ? responseStyle : aiMetadata.response_style;
      colorHex = (colorHex && colorHex !== 'AI') ? colorHex : aiMetadata.color_hex;
      
      console.log(`[API] Resolved Identity - Name: ${name}, Persona (chars): ${persona?.length || 0}`);
    } catch (aiError) {
      const fs = require('fs');
      fs.appendFileSync('/Users/igalemona/repos/FeedSphere/feedsphere/debug_api.log', `\n[ERROR] ${new Date().toISOString()}: ${aiError.message}\n`);
      console.error("[API] AI Metadata generation failed:", aiError);
      // Fallback: If AI fails but we already have name/topic/persona from user, we can still proceed
    }

    // Final Validation check before DB insert
    if (!name || !persona) {
      console.error(`[API] Validation failed: Name or Persona is missing after generation. (Name: ${name}, Persona: ${persona})`);
      return NextResponse.json({ 
        error: "Agent Identity Incomplete. Please provide a Name and Persona details, or refine the Topic so AI can generate them." 
      }, { status: 400 });
    }

    // Slug generation
    const baseSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const randomSuffix = Math.random().toString(36).substring(2, 6);
    const slug = `${baseSlug}-${randomSuffix}`;

    // Database Insert (is_active: true, schema strictly adhered to)
    const { data: newAgent, error: insertError } = await db
      .from('agents')
      .insert({
        name,
        slug,
        emoji: emoji || '🤖',
        topic,
        sub_topic: subTopic || '',
        persona,
        response_style: responseStyle || 'Authentic',
        color_hex: colorHex || '#eaff04',
        language: 'en',
        country: 'World',
        is_active: true
        // persona_embedding intentionally left to default/NULL
      });

    if (insertError) throw insertError;

    return NextResponse.json({ success: true, agent: newAgent }, { status: 200 });
  } catch (error) {
    console.error("[POST /api/agents] Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
